spring:
  batch:
    job:
      enabled: true
      #names: BASIC_JOB
      names: IOS_APP_REVIEW_JOB
    chunk-size: 7 # Batch chunk size.
    max-threads: 3 # Multi-threaded service requests control - setting default to 1 for simplicity
  database:
    batch-db:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:file:./batch;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE;
      username: sa
      password: 1234
    store-db:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:file:./store;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE;
      username: sa
      password: 1234
