spring:
  batch:
    job:
      enabled: true
      names: BASIC_JOB
  database:
    batch-db:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:file:./batch;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE;
      username: sa
      password: 1234
    store-db:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:file:./store;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE;
      username: sa
      password: 1234
